### ISSUE TITLE
Option to measure spacings between element boundaries instead of pixels

### ISSUE THREAD

**Issue by bdbch** [mrflix/dimensions#32]
Right now the plugin only measures spacings between two elements via pixels, so measuring with text or icons can become a bit tricky if the cursor is moved around.

I guess it would make sense to implement an option(*default?*) to measure sizes of DOM elements by their real css dimensions instead of their rendered dimensions.

**Comment by mrflix** [comment]
Try pressing <kbd>ALT</kbd> while measuring. Its an alternative technique that goes around text and other obstacles.

**Comment by db2k** [comment]
@mrflix thats pretty good already, but one issue I have is this for example:

![image](https://cloud.githubusercontent.com/assets/6538827/23606311/7381ac22-0260-11e7-821c-78fdfab57cea.png)

As you can see the plugin is getting the dimensions from the m-character directly, instead of the whole text-block as one. I believe this is interesting and useful for a lot of people but getting back the real spacings between the wrapping element and the child element would also be useful.

Another example are the icons in the navbar of Github.
![image](https://cloud.githubusercontent.com/assets/6538827/23606442/07bd1732-0261-11e7-8655-0b43144c5d55.png)
![image](https://cloud.githubusercontent.com/assets/6538827/23606450/1604e324-0261-11e7-9a7a-b1f446a2793a.png)
![image](https://cloud.githubusercontent.com/assets/6538827/23606465/265b5032-0261-11e7-8469-e21af82f61b2.png)

As you can see the calculated dimensions are changing depending on where I put the cursor relative between the two icons. Shouldn't it pick the outer boundaries of the icons instead?

**Comment by chrisgervang** [comment]
The `alt` feature appears to be broken at the moment when I installed from the chrome store. (it causes the cursor to be very jumpy and laggy).

This is a use case I'd like to use. I've got designs in Sketch, and I use `alt` there to check spacing. I'd love to that with Dimensions too so that I can evaluate sites I work on for areas where the spacing/padding isn't divisible by 8
